package com.ssafy.edu.todo.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo..user.user_seq
     *
     * @mbg.generated
     */
    private Integer userSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo..user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo..user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo..user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo..user.user_seq
     *
     * @return the value of todo..user.user_seq
     *
     * @mbg.generated
     */
    public Integer getUserSeq() {
        return userSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo..user.user_seq
     *
     * @param userSeq the value for todo..user.user_seq
     *
     * @mbg.generated
     */
    public void setUserSeq(Integer userSeq) {
        this.userSeq = userSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo..user.user_name
     *
     * @return the value of todo..user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo..user.user_name
     *
     * @param userName the value for todo..user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo..user.user_id
     *
     * @return the value of todo..user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo..user.user_id
     *
     * @param userId the value for todo..user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo..user.user_password
     *
     * @return the value of todo..user.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo..user.user_password
     *
     * @param userPassword the value for todo..user.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo..user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userSeq=").append(userSeq);
        sb.append(", userName=").append(userName);
        sb.append(", userId=").append(userId);
        sb.append(", userPassword=").append(userPassword);
        sb.append("]");
        return sb.toString();
    }
}